import 'package:flutter/material.dart';
import '../models/order_model.dart';
import '../services/order_service.dart';
import '../models/cart_item.dart';

class CheckoutViewModel extends ChangeNotifier {
  final OrderService _orderService = OrderService();

  bool _isLoading = false;
  String _errorMessage = '';

  bool get isLoading => _isLoading;
  String get errorMessage => _errorMessage;

  Future<bool> processCheckout(String userId, List<CartItem> cartItems, double totalAmount) async {
    if (cartItems.isEmpty) return false;

    _setLoading(true);
    _errorMessage = '';

    try {
      final order = OrderModel(
        id: '', // Will be generated by Firestore
        items: cartItems,
        totalAmount: totalAmount,
        status: 'pending',
        timestamp: DateTime.now(),
      );

      await _orderService.placeOrder(userId, order);
      _setLoading(false);
      return true; // Success
    } catch (e) {
      _errorMessage = e.toString().contains('Exception:') 
        ? e.toString().split('Exception: ').last 
        : "Checkout failed: Please try again.";
      _setLoading(false);
      return false; // Failure
    }
  }

  void _setLoading(bool value) {
    _isLoading = value;
    notifyListeners();
  }
}
