// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQlc88TRWc-CNrgo48ctrD7qRHU3GkyhU',
    appId: '1:305048147048:web:4563cbcfb5feecc2cf17dd',
    messagingSenderId: '305048147048',
    projectId: 'campconnect-a6bf0',
    authDomain: 'campconnect-a6bf0.firebaseapp.com',
    storageBucket: 'campconnect-a6bf0.firebasestorage.app',
    measurementId: 'G-P6X1LYKM03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvcnXK5ui-Z9H-cj3cY9sTlKYOjh3DJfk',
    appId: '1:305048147048:android:0d5fb9745d4aed42cf17dd',
    messagingSenderId: '305048147048',
    projectId: 'campconnect-a6bf0',
    storageBucket: 'campconnect-a6bf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaKALx2sqEK1hJII9V3BQMTd5cMF_mhCk',
    appId: '1:305048147048:ios:d7bfe1f64d8b4135cf17dd',
    messagingSenderId: '305048147048',
    projectId: 'campconnect-a6bf0',
    storageBucket: 'campconnect-a6bf0.firebasestorage.app',
    iosBundleId: 'com.example.campusConncet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaKALx2sqEK1hJII9V3BQMTd5cMF_mhCk',
    appId: '1:305048147048:ios:d7bfe1f64d8b4135cf17dd',
    messagingSenderId: '305048147048',
    projectId: 'campconnect-a6bf0',
    storageBucket: 'campconnect-a6bf0.firebasestorage.app',
    iosBundleId: 'com.example.campusConncet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQlc88TRWc-CNrgo48ctrD7qRHU3GkyhU',
    appId: '1:305048147048:web:3b5718c18c2e57d2cf17dd',
    messagingSenderId: '305048147048',
    projectId: 'campconnect-a6bf0',
    authDomain: 'campconnect-a6bf0.firebaseapp.com',
    storageBucket: 'campconnect-a6bf0.firebasestorage.app',
    measurementId: 'G-2RY8PDF5EJ',
  );
}
