// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC38vnzf4qVhekqRx2WAerTh9pqBb3Oxfs',
    appId: '1:921953135804:web:26faeb2a22efc8c63d74b9',
    messagingSenderId: '921953135804',
    projectId: 'campuseat-7c25c',
    authDomain: 'campuseat-7c25c.firebaseapp.com',
    storageBucket: 'campuseat-7c25c.firebasestorage.app',
    measurementId: 'G-9QPRSW5WXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE1AuRomXkDaP04dwVx2mpAVqRTQiwNQI',
    appId: '1:921953135804:android:5a2a094997bfc8f33d74b9',
    messagingSenderId: '921953135804',
    projectId: 'campuseat-7c25c',
    storageBucket: 'campuseat-7c25c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Dldx403zuqim6V0D5TQWteBBYp314vs',
    appId: '1:921953135804:ios:aae528acd0b419cb3d74b9',
    messagingSenderId: '921953135804',
    projectId: 'campuseat-7c25c',
    storageBucket: 'campuseat-7c25c.firebasestorage.app',
    iosBundleId: 'com.example.week11CampusEat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5Dldx403zuqim6V0D5TQWteBBYp314vs',
    appId: '1:921953135804:ios:aae528acd0b419cb3d74b9',
    messagingSenderId: '921953135804',
    projectId: 'campuseat-7c25c',
    storageBucket: 'campuseat-7c25c.firebasestorage.app',
    iosBundleId: 'com.example.week11CampusEat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC38vnzf4qVhekqRx2WAerTh9pqBb3Oxfs',
    appId: '1:921953135804:web:417fd63d775fc6323d74b9',
    messagingSenderId: '921953135804',
    projectId: 'campuseat-7c25c',
    authDomain: 'campuseat-7c25c.firebaseapp.com',
    storageBucket: 'campuseat-7c25c.firebasestorage.app',
    measurementId: 'G-KCZ7HQYYS4',
  );
}
