// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX-kUbyXqlqKOhejYPncEp7FwYXqQr9C4',
    appId: '1:458645582532:web:c1c7ac5cee07c3702e8f91',
    messagingSenderId: '458645582532',
    projectId: 'mobileappv1-a917a',
    authDomain: 'mobileappv1-a917a.firebaseapp.com',
    storageBucket: 'mobileappv1-a917a.firebasestorage.app',
    measurementId: 'G-PX82PSMWKY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX5gfjwGdvMkM1vdtIRw3YRSWKkSc6nHA',
    appId: '1:458645582532:android:fba9270af7844f7d2e8f91',
    messagingSenderId: '458645582532',
    projectId: 'mobileappv1-a917a',
    storageBucket: 'mobileappv1-a917a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9JFqBzFOuwwJvFGPB-0bTaN96yI7XUaI',
    appId: '1:458645582532:ios:d7993e8423f4665c2e8f91',
    messagingSenderId: '458645582532',
    projectId: 'mobileappv1-a917a',
    storageBucket: 'mobileappv1-a917a.firebasestorage.app',
    iosBundleId: 'com.example.week5Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9JFqBzFOuwwJvFGPB-0bTaN96yI7XUaI',
    appId: '1:458645582532:ios:d7993e8423f4665c2e8f91',
    messagingSenderId: '458645582532',
    projectId: 'mobileappv1-a917a',
    storageBucket: 'mobileappv1-a917a.firebasestorage.app',
    iosBundleId: 'com.example.week5Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX-kUbyXqlqKOhejYPncEp7FwYXqQr9C4',
    appId: '1:458645582532:web:e29adfccbae88a372e8f91',
    messagingSenderId: '458645582532',
    projectId: 'mobileappv1-a917a',
    authDomain: 'mobileappv1-a917a.firebaseapp.com',
    storageBucket: 'mobileappv1-a917a.firebasestorage.app',
    measurementId: 'G-SJ3SG02309',
  );
}
